name: train-validate
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
    run:
      runs-on: [ubuntu-latest]
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.7'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirement.txt

        - name: Train Model
          run: |
            python train.py

        - name: Validate Model
          run: |
            python predict.py 
